# Generated by Django 3.2.13 on 2022-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district_current',
            field=models.CharField(blank=True, max_length=100, verbose_name='Permanent District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district_permanent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Permanent District'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='https://cdn.kites.foundation/img/logo.png', verbose_name='Profile Image Url'),
        ),
    ]
