# Generated by Django 3.2.13 on 2022-05-17 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220517_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$', code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$', code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>')], verbose_name='Whatsapp Number'),
        ),
    ]
